/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.mycompany.guiexample;

import java.awt.Dimension;
import java.awt.Point;

/**
 *
 * @author utsav
 */
public class methodsForGui extends java.awt.Frame {

    /**
     * Creates new form methodsForGui
     */
    public methodsForGui() {
        initComponents();
        setSize(900,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        decreaseSize = new javax.swing.JButton();
        right = new javax.swing.JButton();
        increaseSize = new javax.swing.JButton();
        down = new javax.swing.JButton();
        up = new javax.swing.JButton();
        left = new javax.swing.JButton();
        toggleVisible = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 241, 59));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LABLE");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));

        decreaseSize.setText("SIZE -");
        decreaseSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseSizeActionPerformed(evt);
            }
        });

        right.setText("Right");
        right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightActionPerformed(evt);
            }
        });

        increaseSize.setText("SIZE +");
        increaseSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseSizeActionPerformed(evt);
            }
        });

        down.setText("Down");
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });

        up.setText("Up");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        left.setText("Left");
        left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftActionPerformed(evt);
            }
        });

        toggleVisible.setText("changeVisible");
        toggleVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleVisibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(decreaseSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(down)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(increaseSize)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(toggleVisible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(left)
                        .addGap(60, 60, 60)
                        .addComponent(right)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(up)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(increaseSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decreaseSize)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(left)
                    .addComponent(right)
                    .addComponent(toggleVisible))
                .addGap(5, 5, 5)
                .addComponent(down)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void decreaseSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseSizeActionPerformed
        Dimension d = jLabel1.getSize();
        int w = d.width;
        int h = d.height;
        if(w>=10 && h>=10){
            jLabel1.setSize(w-10,h-10);
        }
    }//GEN-LAST:event_decreaseSizeActionPerformed

    private void rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightActionPerformed
        Point d = jLabel1.getLocation();
        int x = d.x;
        int y = d.y;
        jLabel1.setLocation(x+10, y);
    }//GEN-LAST:event_rightActionPerformed

    private void increaseSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseSizeActionPerformed
        Dimension d = jLabel1.getSize();
        int w = d.width;
        int h = d.height;
        jLabel1.setSize(w+10,h+10);
    }//GEN-LAST:event_increaseSizeActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        Point d = jLabel1.getLocation();
        int x = d.x;
        int y = d.y;
        jLabel1.setLocation(x, y+10);
    }//GEN-LAST:event_downActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        Point d = jLabel1.getLocation();
        int x = d.x;
        int y = d.y;
        jLabel1.setLocation(x, y-10);
    }//GEN-LAST:event_upActionPerformed

    private void leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftActionPerformed
        Point d = jLabel1.getLocation();
        int x = d.x;
        int y = d.y;
        jLabel1.setLocation(x-10, y);
    }//GEN-LAST:event_leftActionPerformed

    private void toggleVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleVisibleActionPerformed
        boolean isVisible = jLabel1.isVisible();
        jLabel1.setVisible(!isVisible);
    }//GEN-LAST:event_toggleVisibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new methodsForGui().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decreaseSize;
    private javax.swing.JButton down;
    private javax.swing.JButton increaseSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton left;
    private javax.swing.JButton right;
    private javax.swing.JButton toggleVisible;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
